refactor: alternate buffer expect message
Wording panic messages like this makes them more readable when they do
show. As an example, here's the before and after of this commit:

thread 'main' panicked at 'to disable alternate buffer'
---
thread 'main' panicked at 'disabling alternate buffer'